name: Node.js Package
on:
    push:
        branches: [ pre ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn install
            - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            - run: git config --local user.name "GitHub Action"
            - run: npm version 1.0.0-pre.${{ github.run_number }}
            - run: npm publish --tag pre
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            # Create Git version tag
            - run: yarn run createTag
